/**
 * GENERATED BY UHV CMS — DO NOT EDIT MANUALLY
 * Edit content in cms/content/ and run Publish from the CMS dashboard.
 * Generated at: 2026-08-30T08:53:33.659Z
 */
window.UHV_NAVIGATION = {
    "items": [
        {
            "label": "Home",
            "href": "index.html",
            "id": "home"
        },
        {
            "label": "About Us",
            "href": "about.html",
            "id": "about"
        },
        {
            "label": "Activities",
            "href": "activities.html",
            "id": "activities"
        },
        {
            "label": "Resources",
            "href": "resources.html",
            "id": "resources"
        },
        {
            "label": "Our Team",
            "href": "team-structure.html",
            "id": "team"
        },
        {
            "label": "Newsletter",
            "href": "newsletter.html",
            "id": "newsletter"
        },
        {
            "label": "Contact",
            "href": "contact.html",
            "id": "contact"
        }
    ],
    "showDownloadApp": true,
    "footerQuickLinks": [
        {
            "label": "Home",
            "href": "index.html"
        },
        {
            "label": "About Us",
            "href": "about.html"
        },
        {
            "label": "Activities",
            "href": "activities.html"
        },
        {
            "label": "Resources",
            "href": "resources.html"
        },
        {
            "label": "Our Team",
            "href": "team-structure.html"
        },
        {
            "label": "Newsletter",
            "href": "newsletter.html"
        },
        {
            "label": "Contact",
            "href": "contact.html"
        }
    ]
};
