/**
 * GENERATED BY UHV CMS — DO NOT EDIT MANUALLY
 * Edit content in cms/content/ and run Publish from the CMS dashboard.
 * Generated at: 2026-08-16T12:25:52.260Z
 */
window.UHV_PAGES = {
    "about": {
        "pageHeader": {
            "title": "About UHV Cell",
            "subtitle": "Journey towards Holistic Human Development"
        },
        "vision": {
            "title": "Our Vision",
            "description": "The UHV Cell aims to foster a deep understanding of human values among students and faculty through self-exploration, reflection, and practice. It supports creating a harmonious society by integrating values into education and nurturing responsible, ethical, and compassionate individuals.",
            "quote": "Existence is Co-existence"
        },
        "objectives": {
            "title": "Key Objectives",
            "items": [
                "To inculcate universal human values like truth, love, peace, responsibility, and justice.",
                "To encourage self-reflection and self-awareness through dialogue-based learning.",
                "To promote ethical and moral development among students and staff.",
                "To integrate values into curriculum, conduct, and campus culture."
            ]
        },
        "coreConcepts": {
            "title": "Core Concepts",
            "cards": [
                {
                    "icon": "fa-user-astronaut",
                    "title": "Self-Exploration",
                    "description": "Understanding one's purpose, role in society, and inner harmony through deep reflection."
                },
                {
                    "icon": "fa-people-roof",
                    "title": "Harmony Levels",
                    "description": "Achieving balance within the individual, with family / society, and with nature."
                },
                {
                    "icon": "fa-hand-holding-heart",
                    "title": "Responsible Living",
                    "description": "Promoting a lifestyle based on need-based living, not greed-based consumption."
                }
            ]
        },
        "whyEssential": {
            "title": "Why UHV is Essential?",
            "cards": [
                {
                    "icon": "fa-seedling",
                    "title": "Holistic Growth",
                    "description": "Develop a comprehensive understanding of human reality and existence through self-exploration."
                },
                {
                    "icon": "fa-hands-holding-circle",
                    "title": "Harmony & Peace",
                    "description": "Learn to live in harmony with oneself, family, society, and the natural environment."
                },
                {
                    "icon": "fa-lightbulb",
                    "title": "Ethical Living",
                    "description": "Cultivate values that lead to a fulfilling, meaningful, and responsible life."
                }
            ]
        }
    },
    "activities": {
        "pageHeader": {
            "title": "Our Activities",
            "subtitle": "Workshops, Talks, and Interactive Sessions"
        },
        "activities": [
            {
                "id": "activity-workshops",
                "icon": "fa-chalkboard-user",
                "headerText": "UHV Workshops",
                "headerColor": "rgba(0, 243, 255, 0.1)",
                "headerTextColor": "var(--primary)",
                "title": "UHV Level 1 & 2 Workshops",
                "description": "Organizing comprehensive 3-8 day workshops for faculty and students to introduce the proposal of Co-existence.",
                "badge": "Ongoing",
                "link": "uhv-workshops.html",
                "linkText": "View Full Gallery"
            },
            {
                "id": "activity-gd",
                "icon": "fa-comments",
                "headerText": "Value Education",
                "headerColor": "rgba(188, 19, 254, 0.1)",
                "headerTextColor": "var(--secondary)",
                "title": "Group Discussions",
                "description": "Conducting weekly dialogue-based sessions where students share their reflections on relationships and society.",
                "badge": "",
                "link": "value-education.html",
                "linkText": "View Full Gallery"
            },
            {
                "id": "activity-talks",
                "icon": "fa-microphone-lines",
                "headerText": "Expert Talks",
                "headerColor": "rgba(255, 0, 85, 0.1)",
                "headerTextColor": "var(--accent)",
                "title": "Invited Resource Persons",
                "description": "Hosting talks by renowned value education experts to deepen understanding of universal values.",
                "badge": "",
                "link": "expert-talks.html",
                "linkText": "View Full Gallery"
            }
        ]
    },
    "contact": {
        "pageHeader": {
            "title": "Get in Touch",
            "subtitle": "We'd be glad to hear your insights and suggestions."
        },
        "contactDetails": {
            "address": "Vidyanagar, Near Kota,\nNellore District (Tirupati Dist),\nAndhra Pradesh - 524413",
            "email": "uhvcell@nbkrist.org",
            "phone": "+91 89858 42025"
        },
        "mapEmbedUrl": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15446.40251781258!2d80.012432!3d14.027681!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a4cf490f2389d31%3A0x4a9d8edfc12f84b3!2sNBKR%20Institute%20of%20Science%20and%20Technology!5e0!3m2!1sen!2sin!4v1710000000000!5m2!1sen!2sin"
    },
    "events": {
        "pageHeader": {
            "title": "Events",
            "subtitle": "Explore our latest events and activities."
        },
        "events": [
            {
                "title": "SAMANVAYA 2K26",
                "imageUrl": "https://i.pinimg.com/originals/08/ec/c1/08ecc11443af02b1f4a9d0edae4f6d0e.png",
                "link": "samanvaya2k26.html",
                "buttonText": "SAMANVAYA 2K26"
            }
        ]
    },
    "expert-talks": {
        "pageHeader": {
            "title": "Expert Talks",
            "subtitle": "Insights shared by invited resource persons."
        },
        "videos": [
            {
                "title": "Expert Talk 1",
                "embedUrl": "https://geo.dailymotion.com/player.html?video=xa3keb0&autoplay=0&ui-logo=0&queue-enable=0&sharing-enable=0&ui-display-sharing=0&ui-display-logo=0&ui-display-cast=1&playsinline=1"
            },
            {
                "title": "Expert Talk 2",
                "embedUrl": "https://geo.dailymotion.com/player.html?video=xa3kmf4&autoplay=0&ui-logo=0&queue-enable=0&sharing-enable=0&ui-display-sharing=0&ui-display-logo=0&ui-display-cast=1&playsinline=1"
            }
        ]
    },
    "footer": {
        "contactEmail": "uhvcell@nbkrist.org",
        "contactPhone": "+91 89858 42025",
        "contactAddress": "Vidyanagar, Nellore District",
        "copyrightText": "UHV CELL NBKRIST"
    },
    "home": {
        "hero": {
            "badge": "NBKRIST UHV Cell",
            "heading": "Empowering Minds with",
            "headingHighlight": "Universal Human Values",
            "description": "Join us in a journey of self-exploration and holistic development. We strive to nurture responsible and ethical individuals for a harmonious society.",
            "primaryButton": {
                "text": "Discover More",
                "link": "team-structure.html"
            },
            "secondaryButton": {
                "text": "Join Us",
                "link": "registration.html"
            }
        },
        "whatsNew": {
            "title": "What's New?",
            "subtitle": "Latest activities and event posters"
        },
        "videos": {
            "title": "Videos",
            "subtitle": "Featured learning resources and sessions"
        },
        "team": {
            "title": "Our Dedicated Team",
            "subtitle": "Click on a member to view details"
        }
    },
    "registration": {
        "pageHeader": {
            "title": "Membership Registration",
            "subtitle": "Join the UHV Cell at NBKRIST and be part of a transformative journey."
        },
        "student": {
            "title": "Student Registration",
            "description": "Click the button below to register as a student member of the UHV Cell.",
            "buttonText": "Register as Student",
            "buttonUrl": "https://forms.gle/96f8V82zZE7HhkUv5"
        },
        "faculty": {
            "title": "Faculty Registration",
            "description": "Click the button below to register as a faculty member or coordinator.",
            "buttonText": "Register as Faculty",
            "buttonUrl": "https://forms.gle/dYDccM3ZyxarzZs1A"
        }
    },
    "resources": {
        "pageHeader": {
            "title": "Resources",
            "subtitle": "Books, Presentations, and Study Materials"
        },
        "resources": [
            {
                "icon": "fa-book-open",
                "title": "UHV Foundation Course",
                "description": "Official textbook and syllabus for Universal Human Values II.",
                "link": "uhv-foundation-course.html",
                "linkText": "View Course Details"
            },
            {
                "icon": "fa-file-powerpoint",
                "title": "Events",
                "description": "Data covering all events of the UHV curriculum.",
                "link": "events.html",
                "linkText": "View Events"
            },
            {
                "icon": "fa-video",
                "title": "Videos",
                "description": "Recorded videos and short films on human values.",
                "link": "videos.html",
                "linkText": "Watch Videos"
            },
            {
                "icon": "fa-image",
                "title": "Posters",
                "description": "Awareness materials, banners and creative visuals on UHV.",
                "link": "posters.html",
                "linkText": "View Posters"
            }
        ]
    },
    "samanvaya2k26": {
        "pageHeader": {
            "title": "SAMANVAYA 2K26",
            "subtitle": "Annual Value Education Fest"
        },
        "logoUrl": "https://i.pinimg.com/originals/08/ec/c1/08ecc11443af02b1f4a9d0edae4f6d0e.png",
        "videoEmbedUrl": "https://geo.dailymotion.com/player.html?video=xa3f5ck&autoplay=0&ui-logo=0&queue-enable=0&sharing-enable=0&ui-display-sharing=0&ui-display-logo=0&ui-display-cast=1&playsinline=1",
        "links": [
            {
                "text": "Event Photos",
                "url": "https://drive.google.com/drive/folders/1Tu842CdMmZFju0agmi8vIM1y7V8C-BmP?usp=sharing",
                "color": "primary"
            },
            {
                "text": "Publicity Photos",
                "url": "https://drive.google.com/drive/folders/1spur-bP_sesXdguHI9VSPQqrrSahey_T?usp=drive_link",
                "color": "secondary"
            },
            {
                "text": "Event Videos",
                "url": "https://drive.google.com/drive/folders/17vTGJpk2zzbDF26D7vJtDJkZXrADvCIu?usp=sharing",
                "color": "accent"
            },
            {
                "text": "Download Participation Certificates",
                "url": "https://drive.google.com/drive/folders/1TXmgy4QMQlivORUTIcpvB6EIdJqaEYbG?usp=sharing",
                "color": "secondary"
            },
            {
                "text": "Download Merit Certificates",
                "url": "https://drive.google.com/drive/folders/1oIegGcsupVeKsWrI97UcvUGiW-vS1QNc?usp=sharing",
                "color": "accent"
            }
        ]
    },
    "uhv-foundation-course": {
        "pageHeader": {
            "title": "UHV Foundation Course",
            "subtitle": "Official textbook and syllabus for Universal Human Values II"
        },
        "overview": {
            "title": "Course Overview",
            "content": "The Universal Human Values (UHV) Foundation Course is designed to help students understand the need for value education. It focuses on the development of a holistic perspective among students towards life, profession, and happiness based on a correct understanding of human reality and the rest of existence.",
            "proceedingsText": "ICHVHE 2025 Proceedings.pdf",
            "proceedingsUrl": "https://drive.google.com/file/d/16jKlBR9_VHXx5Wn3UdB34l9LaB8ebz5P/view?usp=sharing"
        },
        "uhv1Title": "UHV-1 (Introductory Material)",
        "uhv1Materials": [
            {
                "title": "Ind 1 Introductions 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1HHSgabnD_zxYQlGl3V2_eZ2yKExp6Moz/edit?usp=sharing&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 2 Exploring our Aspirations and Concerns 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1DD9bv7j9aN-_TV0cNigyz1MIEY3ij3kJ/edit?usp=sharing&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 3 Basic Human Aspiration & its Fulfilment 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1gzuuZ1ErCN4ipZ_7-AgvGNBKGfXtu7KR/edit?usp=sharing&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 4 Program for Fulfilment of Basic Human Aspiration 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1A8WG6CRFPusvr7mk1m7WdvfySpa6r_XU/edit?usp=sharing&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 5 Fulfilment of Aspirations at Individual Level 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1kEKmedJII6KU5mG8pMMa6OEPbgs01dsX/edit?usp=sharing&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 6 Resolution of Concerns at Individual Level 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1n_8YFu7Zxm87_-FfmrlfbS9GduJMaq0C/edit?usp=sharing&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 7 Ensuring Health 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1Z3gf5Jhb9acFY4sGW6fqXsdSaw3c9SvM/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 8 Fulfilment in Relationship -Trust 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1XFrCU2VjvfcAIl03vts_yHN8dO1wMWAs/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 9 Shifting from Reaction to Response in Relationship 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1QD3B3jroJFNWSAx6KaOtfhKwwI3UQuME/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 10 Fulfilment in Relationship - Respect 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1KgBrcD3bAFpKLgNUsDfUklhjJcMo8qHs/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 11 Shifting from Competition to Excellence 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1ii4v4EMbnwnOjGuxdWrWCchTQPEVH_1q/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 12 Understanding Role in Society 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1I8Cv3vvqm21EBjByBD52NYE9FIiwT8dO/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 13 Understanding Role in Nature 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1sv5KIqjqFpwfPI9TfkX8IlCXqdyLif6R/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 14 Sum Up & Program of Action 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1T5GOd4Ieod8rMieg9mYPNLkvJAbFsVZ2/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "Ind 15 Self-evaluation 2025.pdf",
                "url": "https://docs.google.com/presentation/d/1H0C22kedvH4Ui4I_1DxvoKUIXxYHyfKW/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            }
        ],
        "uhv2Title": "UHV-2",
        "uhv2Materials": [
            {
                "title": "L 1 Holistic Dev & Role of Edu",
                "url": "https://docs.google.com/presentation/d/1WFLIwrQVCStWjjLRyW5PBTdYbmc9Ed3S/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 2 Understanding Value Education v2",
                "url": "https://docs.google.com/presentation/d/1v1sRPGjAjiRVgBAtR_Op_YCxKVC8G5Ki/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 3 Self Exploration v3",
                "url": "https://docs.google.com/presentation/d/1kITMuuNhH46r5zMDOZYDNZw2O4OpOUNp/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 4 Happiness and Prosperity V3",
                "url": "https://docs.google.com/presentation/d/1IXmaxH4cMH7xOy1_IA0OFlmXzcyAr-vh/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 5 Happiness and Prosperity – Current Scenario v2",
                "url": "https://docs.google.com/presentation/d/1GHFn4HyoticT5YG6AuNkE4NJGnGeQfsH/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 6 Method to Fulfill Basic Human Aspirations v2",
                "url": "https://docs.google.com/presentation/d/1wQHDhULBHMh69OfXq6q9-UKoN75xJs94/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 7 HB Self-Body V2",
                "url": "https://docs.google.com/presentation/d/1W4UNRgWyTnuYEi9F1FoOr6uOMBkG5p6y/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 8 HB Needs of Self-Body v2",
                "url": "https://docs.google.com/presentation/d/1a9Yhzh2POIenBk-8tCHb2gbXLhweH0mi/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 9 HB Body - Instrument of Self V3",
                "url": "https://docs.google.com/presentation/d/1jkmgizzO3MWi0JOxW9gv6fVmyAao-j6l/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 10 HB Self V5",
                "url": "https://docs.google.com/presentation/d/1pEVgvN9YX2IGPwBTRsIMi5rewFxrb2xw/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 11 HB Harmony of Self with Body v3",
                "url": "https://docs.google.com/presentation/d/1pEVgvN9YX2IGPwBTRsIMi5rewFxrb2xw/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 12 HB Prog for self-regulation and Health v2",
                "url": "https://docs.google.com/presentation/d/1dVNi6vUuGRpRawkspq5YY8mKbGDkofQb/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 13 Harmony in the Family v4",
                "url": "https://docs.google.com/presentation/d/1U9XDRZJH_FIthbuO-n_Sk5mzcjKrYOfR/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 14 Trust v4",
                "url": "https://docs.google.com/presentation/d/1tm1KeCmbnebgr42iMEJ3YCh1bqBmg7_l/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 15 Respect v6",
                "url": "https://docs.google.com/presentation/d/1fNRsdvNxg4Wtv8xSczmm9jKYkzZcu6v5/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 16 Other Feelings & Justice v3",
                "url": "https://docs.google.com/presentation/d/1d7vUbvUvGGattDhW2sct80gmyoRelJXK/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 17 Harmony in the Society v4",
                "url": "https://docs.google.com/presentation/d/1Xp2t82p_EhPKWzMp2Y-KnanwMK0XDtul/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 18 Vision for the Universal Human Order v2",
                "url": "https://docs.google.com/presentation/d/1bvW4zRgQ7vMj8EtjaDZ9gh2iemFLDexa/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 19 Harmony in Nature v3",
                "url": "https://docs.google.com/presentation/d/16aCbixZu6j7DFBqMviDsD9FE1YecT-Bu/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 20 Mutual Fulfilment in Nature v5",
                "url": "https://docs.google.com/presentation/d/1x6FAi_eLV8mtNkKLJXOhibjsFsPRJwmH/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 21 Existence v9",
                "url": "https://docs.google.com/presentation/d/1CHH2J4b01Y4irrQOAShylIPFyFk9btg3/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 22 Sum Up and Program v3",
                "url": "https://docs.google.com/presentation/d/16IVuJp029bDFEOKdqqmqxRVbblf_3oD1/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 23 Natural Acceptance of Human Values v3",
                "url": "https://docs.google.com/presentation/d/1Oxw_jwDmwJnE41jkPx8q-ll91eIt3zyD/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 24 Definitiveness of (Ethical) Human Conduct v5",
                "url": "https://docs.google.com/presentation/d/156urjt0FbeE3o-mxs1wxJMVghja_ZS5D/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 25 A Basis for Humane Society v4",
                "url": "https://docs.google.com/presentation/d/1yfzRJ9t-AnlRsbEQ354OfXExg1eRhfmB/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 26 Holistic Development towards Humane Society & Traditiion v5",
                "url": "https://docs.google.com/presentation/d/19WW7mhyJ9ZS5Z8gjBDMuip5dG3UlxKGp/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 27 Holistic Technologies v5",
                "url": "https://docs.google.com/presentation/d/1ckApeVKljyLf-eAQqTGuCu5loJPdDJjt/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            },
            {
                "title": "L 28 Strategies for Transition v4",
                "url": "https://docs.google.com/presentation/d/1SmR7UvT1cRXcVj00btcgo9GOoFUCbvvp/edit?usp=drive_link&ouid=118042007280036017273&rtpof=true&sd=true"
            }
        ]
    },
    "uhv-workshops": {
        "pageHeader": {
            "title": "UHV Workshops",
            "subtitle": "Capturing moments from our Level 1 & 2 value education workshops"
        },
        "days": [
            {
                "title": "DAY 1 SDG PANEL DISCUSSION",
                "titleColor": "var(--primary)",
                "images": [
                    "sdg_day1_3.jpg",
                    "sdg_day1_1.jpg",
                    "sdg_day1_2.jpg",
                    "sdg_day1_4.jpg"
                ]
            },
            {
                "title": "DAY 2 WORKSHOP SESSIONS",
                "titleColor": "var(--secondary)",
                "images": [
                    "sdg_day2_1.jpg",
                    "sdg_day2_2.jpg"
                ]
            },
            {
                "title": "DAY 3 CONCLUDING CEREMONY",
                "titleColor": "#a855f7",
                "images": [
                    "sdg_day3_1.jpg",
                    "sdg_day3_2.jpg",
                    "sdg_day3_3.jpg"
                ]
            }
        ]
    },
    "value-education": {
        "pageHeader": {
            "title": "Value Education",
            "subtitle": "Dialogue and self-reflection sessions with students."
        },
        "videoSection": {
            "title": "Group Discussions Video",
            "embedUrl": "https://geo.dailymotion.com/player.html?video=xa2rzvy&autoplay=0&ui-logo=0&queue-enable=0&sharing-enable=0&ui-display-sharing=0&ui-display-logo=0&ui-display-cast=1&playsinline=1"
        },
        "documentSection": {
            "title": "RC&UC 2026 PPT",
            "linkText": "Document Link",
            "url": "https://docs.google.com/presentation/d/14whCKkXWM66TZntuaCJOezp-eGF6mDCH/edit?usp=sharing&ouid=118042007280036017273&rtpof=true&sd=true"
        }
    }
};
