/**
 * GENERATED BY UHV CMS — DO NOT EDIT MANUALLY
 * Edit content in cms/content/ and run Publish from the CMS dashboard.
 * Generated at: 2026-08-30T08:53:33.654Z
 */
// Shared Team Data

const defaultFacultyCoordinators = [
    {
        "name": "Dr. M. Srinivasulu",
        "role": "Administrator",
        "department": "Administrator",
        "detail": "Principal, NBKRIST",
        "image": "srinivasulu.jpg",
        "icon": "fa-user-tie",
        "special": true,
        "isLead": false
    },
    {
        "name": "Smt. B. Raghavamma",
        "role": "General Secretary",
        "department": "General Secretary",
        "detail": "Dept. of S&H",
        "image": "raghavamma.jpg",
        "icon": "fa-chalkboard-user",
        "special": true
    },
    {
        "name": "Mr. K. Narendra",
        "role": "Joint Secretary",
        "department": "Joint Secretary",
        "detail": "Dept. of S&H",
        "image": "narendra.jpg",
        "icon": "fa-user",
        "special": true
    }
];

const defaultStudentCoordinators = [
    {
        "name": "T. Varunemdhar Reddy",
        "role": "President",
        "department": "President",
        "detail": "Student Body President",
        "image": "varun.jpg",
        "icon": "fa-graduation-cap",
        "special": true
    },
    {
        "name": "K. Rithika Reddy",
        "role": "Vice President",
        "department": "Vice President",
        "detail": "Student Body Vice President",
        "image": "rithika.jpg",
        "icon": "fa-user-graduate",
        "special": true
    },
    {
        "name": "P. Charuhaaini",
        "role": "Volunteer",
        "department": "Volunteers Team",
        "detail": "Volunteers Wing",
        "image": "charuhaaini.jpg",
        "icon": "fa-user-graduate",
        "special": false,
        "isLead": false
    },
    {
        "name": "N. Prathyush",
        "role": "Co-Coordinator",
        "department": "Innovation Team",
        "detail": "Innovation Wing",
        "image": "prathyush.jpg",
        "icon": "fa-user-graduate",
        "special": false,
        "isLead": false
    },
    {
        "name": "K. Chandu",
        "role": "Volunteer",
        "department": "Volunteers Team",
        "detail": "Volunteers Wing",
        "image": "chandu.jpg",
        "icon": "fa-user-graduate",
        "special": false,
        "isLead": false
    },
    {
        "name": "G. Lakshmidhar Reddy",
        "role": "Co-Coordinator",
        "department": "Technical Team",
        "detail": "Technical Wing",
        "image": "lakshmidhar.png",
        "icon": "fa-code",
        "special": false,
        "isLead": false
    },
    {
        "name": "M. Manoj",
        "role": "Co-Coordinator",
        "department": "Technical Team",
        "detail": "Technical Wing",
        "image": "manoj.jpg",
        "icon": "fa-code-branch",
        "special": true,
        "isLead": false
    },
    {
        "name": "M Rishithanjali Reddy",
        "role": "Co-Coordinator",
        "department": "Technical Team",
        "detail": "Technical Wing",
        "image": "rishithanjali.jpg",
        "icon": "fa-code-branch",
        "special": false,
        "isLead": false
    },
    {
        "name": "V. Hemanth Krishna",
        "role": "Co-Coordinator",
        "department": "Design Team",
        "detail": "Design & Skill Wing",
        "image": "hemanth_krishna.jpg",
        "icon": "fa-pencil-ruler",
        "special": false,
        "isLead": false
    },
    {
        "name": "SK. Latheef",
        "role": "Co-Coordinator",
        "department": "Design Team",
        "detail": "Design & Skill Wing",
        "image": "latheef.jpg",
        "icon": "fa-user-pen",
        "special": false,
        "isLead": false
    },
    {
        "name": "Y. Mahidhar Reddy",
        "role": "Coordinator",
        "department": "Innovation Team",
        "detail": "Innovation Wing",
        "image": "mahidhar.png",
        "icon": "fa-file-lines",
        "special": true,
        "isLead": true
    },
    {
        "name": "A. Gayathri",
        "role": "Co-Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing",
        "image": "gayathri.jpg",
        "icon": "fa-file-pen",
        "special": false,
        "isLead": false
    },
    {
        "name": "C Divya",
        "role": "Co-Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing",
        "image": "divya.jpg",
        "icon": "fa-file-pen",
        "special": false,
        "isLead": false
    },
    {
        "name": "A Ajay Kumar",
        "role": "Co-Coordinator",
        "department": "Innovation Team",
        "detail": "Innovation Wing",
        "image": "ajay_kumar.jpg",
        "icon": "fa-file-pen",
        "special": false,
        "isLead": false
    },
    {
        "name": "P. Lokanadh",
        "role": "Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing ",
        "image": "lokanadh.jpg",
        "icon": "fa-file-lines",
        "special": true,
        "isLead": true
    },
    {
        "name": "P Narmadha",
        "role": "Coordinator",
        "department": "Design Team",
        "detail": "Design & Skill Wing",
        "image": "narmadha.jpg",
        "icon": "fa-user",
        "special": true,
        "isLead": true
    },
    {
        "name": "K Nandha Kishore Reddy",
        "role": "Coordinator",
        "department": "Technical Team",
        "detail": "Technical Wing",
        "image": "nandha.jpg",
        "icon": "fa-user",
        "special": true,
        "isLead": true
    },
    {
        "name": "V Uday Lakshmi",
        "role": "Co-Coordinator",
        "department": "Technical Team",
        "detail": "Technical Wing",
        "image": "udaylakshmi.jpg",
        "icon": "fa-user",
        "special": false,
        "isLead": false
    },
    {
        "name": "Y Mukundha",
        "role": "Co-Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing",
        "image": "mukundha.jpg",
        "icon": "fa-user",
        "special": false,
        "isLead": false
    },
    {
        "name": "E Abhijith",
        "role": "Co-Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing",
        "image": "abhijith,jpg",
        "icon": "fa-user",
        "special": false,
        "isLead": false
    },
    {
        "name": "V Brahmani",
        "role": "Co-Coordinator",
        "department": "Design Team",
        "detail": "Design & Skill Wing",
        "image": "brahmani.jpg",
        "icon": "fa-user",
        "special": false,
        "isLead": false
    },
    {
        "name": "P Kaveri",
        "role": "Co-Coordinator",
        "department": "Innovation Team",
        "detail": "Innovation Wing",
        "image": "kaveri.jpg",
        "icon": "fa-user",
        "special": false,
        "isLead": false
    },
    {
        "name": "K Rakshitha ",
        "role": "Co-Coordinator",
        "department": "Innovation Team",
        "detail": "Innovation Wing",
        "image": "",
        "icon": "fa-user",
        "special": false,
        "isLead": false
    }
];

const facultyCoordinators = defaultFacultyCoordinators;
const studentCoordinators = defaultStudentCoordinators;
const allTeamMembers = [...facultyCoordinators, ...studentCoordinators];
