/**
 * GENERATED BY UHV CMS — DO NOT EDIT MANUALLY
 * Edit content in cms/content/ and run Publish from the CMS dashboard.
 * Generated at: 2026-08-16T12:25:52.234Z
 */
// Shared Team Data

const defaultFacultyCoordinators = [
    {
        "name": "Dr. M. Srinivasulu",
        "role": "Administrator",
        "department": "Administrator",
        "detail": "Principal, NBKRIST",
        "image": "srinivasulu.jpg",
        "icon": "fa-user-tie",
        "special": true
    },
    {
        "name": "Smt. B. Raghavamma",
        "role": "General Secretary",
        "department": "General Secretary",
        "detail": "Dept. of S&H",
        "image": "raghavamma.jpg",
        "icon": "fa-chalkboard-user",
        "special": true
    },
    {
        "name": "Mr. K. Narendra",
        "role": "Joint Secretary",
        "department": "Joint Secretary",
        "detail": "Dept. of S&H",
        "image": "narendra.jpg",
        "icon": "fa-user",
        "special": true
    }
];

const defaultStudentCoordinators = [
    {
        "name": "T. Varunemdhar Reddy",
        "role": "President",
        "department": "President",
        "detail": "Student Body President",
        "image": "varun.jpg",
        "icon": "fa-graduation-cap",
        "special": true
    },
    {
        "name": "K. Rithika Reddy",
        "role": "Vice President",
        "department": "Vice President",
        "detail": "Student Body Vice President",
        "image": "rithika.jpg",
        "icon": "fa-user-graduate",
        "special": true
    },
    {
        "name": "P. Charuhaaini",
        "role": "Volunteer",
        "department": "Volunteers Team",
        "detail": "Volunteers Wing",
        "image": "charuhaaini.jpg",
        "icon": "fa-user-graduate",
        "special": false,
        "isLead": false
    },
    {
        "name": "N. Prathyush",
        "role": "Student Co-Coordinator",
        "department": "Volunteers Team",
        "detail": "Volunteers Wing",
        "icon": "fa-user-graduate",
        "image": "prathyush.jpg",
        "special": false
    },
    {
        "name": "K. Chandu",
        "role": "Student Co-Coordinator",
        "department": "Volunteers Team",
        "detail": "Volunteers Wing",
        "icon": "fa-user-graduate",
        "image": "chandu.jpg",
        "special": false,
        "isLead": false
    },
    {
        "name": "G. LAKSHMIDHAR REDDY",
        "role": "TECHNICAL COORDINATOR",
        "department": "Technical Team",
        "detail": "Tech Wing Lead",
        "icon": "fa-code",
        "image": "lakshmidhar.png",
        "special": true
    },
    {
        "name": "M. Manoj",
        "role": "Technical Co-Coordinator",
        "department": "Technical Team",
        "detail": "Technical Wing",
        "icon": "fa-code-branch",
        "image": "manoj.jpg",
        "special": false
    },
    {
        "name": "R. Mahesh",
        "role": "Technical Co-Coordinator",
        "department": "Technical Team",
        "detail": "Technical Wing",
        "icon": "fa-code-branch",
        "image": "mahesh.jpg",
        "special": false
    },
    {
        "name": "V. Rakshitha Reddy",
        "role": "Skill Co-Coordinator",
        "department": "Design Team",
        "detail": "Design & Skill Wing",
        "icon": "fa-pencil-ruler",
        "image": "rakshitha.jpg",
        "special": false
    },
    {
        "name": "SK. Latheef",
        "role": "Skill Co-Coordinator",
        "department": "Design Team",
        "detail": "Design & Skill Wing",
        "icon": "fa-user-pen",
        "image": "latheef.jpg",
        "special": false,
        "isLead": false
    },
    {
        "name": "Y. Mahidhar Reddy",
        "role": "Content Coordinator",
        "department": "Innovation Team",
        "detail": "Innovation Wing",
        "image": "mahidhar.png",
        "icon": "fa-file-lines",
        "special": false,
        "isLead": true
    },
    {
        "name": "A. Ajay Kumar",
        "role": "Content Co-Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing",
        "image": "ajay_kumar.jpg",
        "icon": "fa-file-pen",
        "special": false
    },
    {
        "name": "O. Penchal Das",
        "role": "Content Co-Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing",
        "icon": "fa-file-pen",
        "image": "penchal_das.jpg",
        "special": false
    },
    {
        "name": "G. Varalakshmi",
        "role": "Content Co-Coordinator",
        "department": "Innovation Team",
        "detail": "Innovation Wing",
        "icon": "fa-file-pen",
        "image": "varalakshmi.jpg",
        "special": false,
        "isLead": false
    },
    {
        "name": "P. Lokanadh",
        "role": "Content Co-Coordinator",
        "department": "Marketing Team",
        "detail": "Marketing & Content Wing ",
        "image": "lokanadh.jpg",
        "icon": "fa-file-lines",
        "special": true,
        "isLead": true
    }
];

const facultyCoordinators = defaultFacultyCoordinators;
const studentCoordinators = defaultStudentCoordinators;
const allTeamMembers = [...facultyCoordinators, ...studentCoordinators];
