/**
 * GENERATED BY UHV CMS — DO NOT EDIT MANUALLY
 * Edit content in cms/content/ and run Publish from the CMS dashboard.
 * Generated at: 2026-08-16T12:25:52.237Z
 */
const defaultVideoResources = [
    {
        "title": "The Deadline Disaster",
        "description": "A short film on managing time and values.",
        "thumbnail": "https://archive.org/services/img/CEP120",
        "videoUrl": "https://archive.org/details/CEP120",
        "type": "Short Film"
    },
    {
        "title": "Change Begins WithIn",
        "description": "Exploring personal transformation.",
        "thumbnail": "https://archive.org/services/img/The_Great_Train_Robbery_1903",
        "videoUrl": "https://archive.org/details/The_Great_Train_Robbery_1903",
        "type": "Reflections"
    },
    {
        "title": "One Attempt",
        "description": "A story about perseverance and integrity.",
        "thumbnail": "https://archive.org/services/img/CC_1914_05_04_CaughtInARain",
        "videoUrl": "https://archive.org/details/CC_1914_05_04_CaughtInARain",
        "type": "Educational"
    }
];

const videoResources = defaultVideoResources;
