/**
 * GENERATED BY UHV CMS — DO NOT EDIT MANUALLY
 * Edit content in cms/content/ and run Publish from the CMS dashboard.
 * Generated at: 2026-08-30T08:53:33.655Z
 */
const defaultVideoResources = [
    {
        "title": "The Deadline Disaster",
        "type": "Workshop",
        "videoUrl": "https://archive.org/download/the-deadline-disaster-2-16-2026-12-18-pm/The%20Deadline%20Disaster-2_16_2026%2C%2012_18%E2%80%AFPM.mp4",
        "videoId": "https://archive.org/download/the-deadline-disaster-2-16-2026-12-18-pm/The%20Deadline%20Disaster-2_16_2026%2C%2012_18%E2%80%AFPM.mp4",
        "thumbnail": "",
        "description": "A short film on managing time and values."
    },
    {
        "title": "Change Begins WithIn",
        "type": "Workshop",
        "videoUrl": "https://archive.org/download/change-begins-with-in-2-16-2026-12-17-pm/Change%20Begins%20WithIn-2_16_2026%2C%2012_17%E2%80%AFPM.mp4",
        "videoId": "https://archive.org/download/change-begins-with-in-2-16-2026-12-17-pm/Change%20Begins%20WithIn-2_16_2026%2C%2012_17%E2%80%AFPM.mp4",
        "thumbnail": "",
        "description": "Exploring personal transformation."
    },
    {
        "title": "One Attempt",
        "type": "Workshop",
        "videoUrl": "https://archive.org/download/one-attempt-2-16-2026-10-18-pm/One%20Attempt%202_16_2026%2C%2010_18%E2%80%AFPM.mp4",
        "videoId": "https://archive.org/download/one-attempt-2-16-2026-10-18-pm/One%20Attempt%202_16_2026%2C%2010_18%E2%80%AFPM.mp4",
        "thumbnail": "",
        "description": "A story about perseverance and integrity."
    }
];

const videoResources = defaultVideoResources;
